import type { Metadata } from "next";
import "./globals.css";
import { yekanBakh } from "@/lib/font";
import Header from "@/components/common/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={` ${yekanBakh.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
        
        </body>
    </html>
  );
}
